# Generated by Django 2.2.4 on 2020-06-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Save_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.BigIntegerField()),
                ('product', models.CharField(max_length=200)),
                ('proposal_no', models.BigIntegerField()),
                ('inwardnumber', models.CharField(max_length=250)),
                ('currentworkstep', models.CharField(max_length=200)),
                ('names', models.CharField(max_length=100)),
                ('customer_names', models.CharField(max_length=200)),
            ],
        ),
    ]
